"""Injects a small JS "render-time translation" patch into the game so text
the static data/*.json editing can't reach (plugin-parameter strings,
dynamically-built labels, ...) still shows up in Korean on screen, without
touching plugins.js or any other source file at all.

How it works: RPG Maker's core funnels essentially all window text through
Window_Base.prototype.convertEscapeCharacters (before \\V[n]/\\N[n]/... get
resolved) and/or Window_Base.prototype.drawText (for plain strings with no
escape codes). This patch wraps both, and right before the original runs,
swaps the *raw* pre-resolution string for its Korean translation if one
exists in our cache -- so "好感度 \\V[43]" gets swapped for "호감도 \\V[43]"
and \\V[43] still resolves normally afterwards, inside the Korean text.
The underlying data stays byte-for-byte original; only what gets *drawn*
changes.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from engine import ProjectLayout

PATCH_FILENAME = "korean_patch.js"

_PATCH_TEMPLATE = """\
// Auto-generated by the RPG Maker Korean localizer -- do not edit by hand,
// it gets regenerated (and overwritten) on every translation run.
// Wraps RPG Maker's core text-drawing functions so any text present in
// TRANSLATIONS below shows up in Korean on screen, without touching any
// other source file (data/*.json, plugins.js, ...) at all.
(function() {{
    var TRANSLATIONS = {translations_json};

    // Debug aid: every unique string that ever passes through one of the
    // hooks below (matched or not) gets recorded here, capped so it can't
    // grow unbounded. If DevTools (F12) is available, inspect it with e.g.:
    //   Array.from(window.__koPatchSeen).filter(function(s){{return /행동|好感|行動/.test(s);}})
    // Many packaged NW.js games disable DevTools outright, so this also
    // dumps the same set to a plain text file next to the game folder
    // every few seconds (using Node's fs, which NW.js exposes by default)
    // -- no DevTools access needed, just open ko_patch_debug.txt in Notepad.
    window.__koPatchSeen = window.__koPatchSeen || new Set();

    var _sortedKeys = null;
    function sortedKeys() {{
        if (!_sortedKeys) {{
            // longest key first, so e.g. a whole-line entry matches before
            // a shorter label fragment inside it steals part of the string
            _sortedKeys = Object.keys(TRANSLATIONS).sort(function(a, b) {{
                return b.length - a.length;
            }});
        }}
        return _sortedKeys;
    }}

    // fillText/strokeText fire on essentially every frame a message window
    // is mid-typewriter-effect, so re-running the substring-fallback scan
    // (below) for the same repeated string every time would be wasteful.
    // Cache each text's resolved result once and reuse it; capped like
    // __koPatchSeen so a game with endless unique strings (procedurally
    // generated numbers embedded in text, say) can't grow this forever.
    var _lookupCache = new Map();

    function lookup(text) {{
        if (typeof text !== "string" || text.length === 0) {{
            return text;
        }}
        if (window.__koPatchSeen.size < 3000) {{
            window.__koPatchSeen.add(text);
        }}
        if (Object.prototype.hasOwnProperty.call(TRANSLATIONS, text)) {{
            return TRANSLATIONS[text];
        }}
        var cached = _lookupCache.get(text);
        if (cached !== undefined) {{
            return cached;
        }}
        // Fallback: some HUD/gauge plugins rebuild their label text at draw
        // time (e.g. appending a live stat value), so the exact line
        // harvested from data/*.json may never appear on screen verbatim.
        // Replace any known Japanese fragment found inside the string
        // instead of requiring a full match.
        var keys = sortedKeys();
        var result = text;
        var changed = false;
        for (var i = 0; i < keys.length; i++) {{
            var key = keys[i];
            if (key.length < 2 || result.indexOf(key) === -1) continue;
            result = result.split(key).join(TRANSLATIONS[key]);
            changed = true;
        }}
        var resolved = changed ? result : text;
        if (_lookupCache.size < 5000) {{
            _lookupCache.set(text, resolved);
        }}
        return resolved;
    }}

    try {{
        if (typeof require === "function") {{
            var fs = require("fs");
            var path = require("path");
            var debugPath = path.join(process.cwd(), "ko_patch_debug.txt");
            var lastSize = -1;
            setInterval(function() {{
                if (window.__koPatchSeen.size === lastSize) return;
                lastSize = window.__koPatchSeen.size;
                var lines = Array.from(window.__koPatchSeen).sort();
                fs.writeFileSync(debugPath, lines.join("\\n"), "utf-8");
            }}, 3000);
        }}
    }} catch (e) {{
        // Node not exposed to this window (nodeIntegration off) -- DevTools
        // (if available) is the only way to inspect __koPatchSeen then.
    }}

    if (typeof Window_Base !== "undefined") {{
        if (Window_Base.prototype.convertEscapeCharacters) {{
            var _convertEscapeCharacters = Window_Base.prototype.convertEscapeCharacters;
            Window_Base.prototype.convertEscapeCharacters = function(text) {{
                return _convertEscapeCharacters.call(this, lookup(text));
            }};
        }}
        if (Window_Base.prototype.drawText) {{
            var _drawText = Window_Base.prototype.drawText;
            Window_Base.prototype.drawText = function(text, x, y, width, align) {{
                return _drawText.call(this, lookup(text), x, y, width, align);
            }};
        }}
    }}

    // Custom UI (a Sprite drawing straight onto its own Bitmap instead of
    // going through a proper Window_Base subclass -- common for HUD-style
    // widgets like a floating stat display) never reaches the hooks above
    // at all, since it skips Window_Base entirely. Bitmap.prototype.drawText
    // is the lowest-level primitive practically everything -- including
    // Window_Base's own drawText -- funnels through in the end, so hooking
    // it here catches those cases too. (Text with escape codes still needs
    // the Window_Base.convertEscapeCharacters hook above: by the time a
    // \\V[n]-bearing string reaches Bitmap.drawText it's already been split
    // into small per-run fragments, which won't match a whole-string cache
    // lookup; plain labels with no escape codes arrive here whole.)
    if (typeof Bitmap !== "undefined" && Bitmap.prototype.drawText) {{
        var _bitmapDrawText = Bitmap.prototype.drawText;
        Bitmap.prototype.drawText = function(text, x, y, width, height, align) {{
            return _bitmapDrawText.call(this, lookup(text), x, y, width, height, align);
        }};
    }}

    // Last-resort safety net: some custom HUD/gauge plugins draw straight
    // onto a canvas 2D context themselves (ctx.fillText/strokeText),
    // skipping Bitmap.prototype.drawText entirely -- a plugin implementing
    // its own outline-width tag (like \\ow[n]) is a typical case, since it
    // needs to control stroke width manually. fillText/strokeText is the
    // lowest-level text primitive the browser itself provides, so hooking
    // it here catches those too, no matter what sits above it.
    if (typeof CanvasRenderingContext2D !== "undefined") {{
        var _fillText = CanvasRenderingContext2D.prototype.fillText;
        CanvasRenderingContext2D.prototype.fillText = function(text, x, y, maxWidth) {{
            text = lookup(text);
            if (maxWidth === undefined) {{
                return _fillText.call(this, text, x, y);
            }}
            return _fillText.call(this, text, x, y, maxWidth);
        }};
        var _strokeText = CanvasRenderingContext2D.prototype.strokeText;
        CanvasRenderingContext2D.prototype.strokeText = function(text, x, y, maxWidth) {{
            text = lookup(text);
            if (maxWidth === undefined) {{
                return _strokeText.call(this, text, x, y);
            }}
            return _strokeText.call(this, text, x, y, maxWidth);
        }};
    }}
}})();
"""

_SCRIPT_TAG = f'<script type="text/javascript" src="js/{PATCH_FILENAME}"></script>'


def build_translation_map(cache_data: dict[str, str]) -> dict[str, str]:
    """Only entries that actually changed are worth shipping in the patch --
    skips fallback-to-source ones (translated == source) so the map stays
    small and a lookup miss is the common, cheap case."""
    return {src: dst for src, dst in cache_data.items() if dst and dst != src}


def inject_render_patch(layout: ProjectLayout, translations: dict[str, str]) -> Optional[Path]:
    """Writes js/korean_patch.js and adds a <script> tag for it to
    index.html (once; safe to call again on a re-run). Returns the patch
    file path, or None if index.html wasn't found at the expected spot."""
    index_html = layout.root / "index.html"
    if not index_html.exists():
        return None

    js_dir = layout.root / "js"
    js_dir.mkdir(parents=True, exist_ok=True)
    patch_path = js_dir / PATCH_FILENAME

    translations_json = json.dumps(translations, ensure_ascii=False)
    patch_path.write_text(
        _PATCH_TEMPLATE.format(translations_json=translations_json), encoding="utf-8"
    )

    html = index_html.read_text(encoding="utf-8")
    if _SCRIPT_TAG not in html:
        html = _insert_script_tag(html)
        index_html.write_text(html, encoding="utf-8")

    return patch_path


def _insert_script_tag(html: str) -> str:
    """Places the patch's <script> tag as early as it safely can go: right
    before plugins.js (or main.js, if plugins.js isn't found -- some very
    old MV layouts skip it), so the hooks are installed before any plugin
    or game-start code runs. Loading it after main.js (simplest, and what
    an earlier version of this did) leaves a real race: if a Common Event
    fires text-drawing plugin commands as part of the game's very first
    auto-run event, some of those calls can happen before a script tag
    positioned near </body> has even finished loading, let alone executed
    -- which looks exactly like "some labels translate, others right next
    to them don't", because it depends on load timing, not on any actual
    lookup failure. Falls back to right before </body> if neither anchor
    is found, so the patch still gets loaded somehow."""
    for anchor in ('src="js/plugins.js"', 'src="js/main.js"'):
        idx = html.find(anchor)
        if idx == -1:
            continue
        line_start = html.rfind("<script", 0, idx)
        if line_start == -1:
            continue
        return html[:line_start] + f"{_SCRIPT_TAG}\n        " + html[line_start:]
    if "</body>" in html:
        return html.replace("</body>", f"    {_SCRIPT_TAG}\n</body>")
    return html + f"\n{_SCRIPT_TAG}\n"
